# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "313fd7080b0a4a0cfbe43f41dfdf59f9"
name = "CamoSignal Upsell"
application_url = "https://camosignal-upsell.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_locations,write_app_proxy,write_discounts,read_orders,write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://camosignal-upsell.vercel.app/auth/callback",
]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update", "products/delete" ]
  uri = "/webhooks/products/sync"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[app_proxy]
url = "/apps/flex-cart-upsell"
prefix = "apps"
subpath = "flex-cart-upsell-1"

[build]
automatically_update_urls_on_dev = true
