import type { AppAnalysis, DailyPoint } from "@/lib/types";

const productImages = {
  tetonMap:
    "https://cdn.shopify.com/s/files/1/0741/7987/0911/files/GrandTetonNationalParkIllustratedMapT-shirt_5.jpg?v=1781669540",
  trout:
    "https://cdn.shopify.com/s/files/1/0741/7987/0911/files/TroutSpeciesOfTheAppalachianMountainsT-shirt_6.jpg?v=1781667303",
  mahi:
    "https://cdn.shopify.com/s/files/1/0741/7987/0911/files/MahiStrikeOffshoreT-shirt_3.jpg?v=1781666070",
  turkey:
    "https://cdn.shopify.com/s/files/1/0741/7987/0911/files/WildTurkeyRunT-shirt_4.jpg?v=1781577163",
  lake:
    "https://cdn.shopify.com/s/files/1/0741/7987/0911/files/It_sLakeTimeT-shirt_3.jpg?v=1781506160",
  hunting:
    "https://cdn.shopify.com/s/files/1/0741/7987/0911/files/OffHuntingSeasonT-shirt_5.jpg?v=1781505559",
};

const daily: DailyPoint[] = [
  { date: "2026-06-03", netSales: 6710, orders: 72, sessions: 3710 },
  { date: "2026-06-04", netSales: 6110, orders: 68, sessions: 3490 },
  { date: "2026-06-05", netSales: 5480, orders: 61, sessions: 3380 },
  { date: "2026-06-06", netSales: 5190, orders: 57, sessions: 3270 },
  { date: "2026-06-07", netSales: 5030, orders: 55, sessions: 3220 },
  { date: "2026-06-08", netSales: 4860, orders: 54, sessions: 3310 },
  { date: "2026-06-09", netSales: 5040, orders: 59, sessions: 3500 },
  { date: "2026-06-10", netSales: 2427, orders: 57, sessions: 3440 },
  { date: "2026-06-11", netSales: 2840, orders: 63, sessions: 3520 },
  { date: "2026-06-12", netSales: 3195, orders: 70, sessions: 3610 },
  { date: "2026-06-13", netSales: 2760, orders: 61, sessions: 3490 },
  { date: "2026-06-14", netSales: 3480, orders: 78, sessions: 3720 },
  { date: "2026-06-15", netSales: 3915, orders: 88, sessions: 3890 },
  { date: "2026-06-16", netSales: 4218, orders: 94, sessions: 4010 },
];

function productDaily(base: number, orders: number): DailyPoint[] {
  const weights = [0.08, 0.1, 0.07, 0.09, 0.11, 0.12, 0.1, 0.06, 0.05, 0.06, 0.04, 0.05, 0.04, 0.03];
  return daily.map((day, index) => ({
    date: day.date,
    netSales: Math.round(base * weights[index]),
    orders: Math.max(0, Math.round(orders * weights[index])),
  }));
}

export const sampleAnalysis: AppAnalysis = {
  generatedAt: "2026-06-17T09:21:00-04:00",
  periodLabel: "Last 14 days",
  comparisonLabel: "Previous 14 days",
  currency: "USD",
  coverage: {
    shopify: "live",
    metaAds: "manual",
  },
  metrics: [
    { label: "Net sales", value: "$58,255", delta: 0.046, helper: "Shopify orders, refunds removed" },
    { label: "Orders", value: "897", delta: 0.118, helper: "Unique Shopify orders" },
    { label: "AOV", value: "$64.94", delta: -0.055, helper: "Net sales / orders" },
    { label: "Discount rate", value: "18.89%", delta: 0.091, helper: "Discounts / gross sales" },
    { label: "Refund rate", value: "0.8%", delta: -0.012, helper: "Refunds / gross sales" },
    { label: "ROAS", value: "No data", delta: null, helper: "Connect Meta Ads for spend" },
  ],
  customerLifecycle: {
    available: true,
    newCustomerRevenueShare: 0.37,
    returningRevenueShare: 0.57,
    unknownRevenueShare: 0.06,
    newCustomerDiscountRate: 0.126,
    returningDiscountRate: 0.224,
    diagnosis:
      "Returning customers are carrying more than half of revenue while using a higher discount rate. That can be healthy retention, but Meta spend should not scale new-customer acquisition until new-customer discount pressure is checked.",
    rows: [
      {
        segment: "returning",
        label: "Returning customers",
        revenue: 33205,
        orders: 492,
        discounts: 9580,
        grossSales: 42785,
        share: 0.57,
        aov: 67.49,
        discountRate: 0.224,
      },
      {
        segment: "new",
        label: "First-time customers",
        revenue: 21554,
        orders: 344,
        discounts: 3108,
        grossSales: 24662,
        share: 0.37,
        aov: 62.66,
        discountRate: 0.126,
      },
      {
        segment: "unknown",
        label: "Guest / unmatched",
        revenue: 3496,
        orders: 61,
        discounts: 510,
        grossSales: 4006,
        share: 0.06,
        aov: 57.31,
        discountRate: 0.127,
      },
    ],
  },
  growth: {
    current: {
      humanSessions: 49560,
      uniqueBuyers: 724,
      guestOrders: 61,
      estimatedPopupSignups: 1486,
      estimatedPopupSignupBuyers: 74,
      popupAudienceBuyers: 198,
      popupAudienceRevenue: 14420,
    },
    previous: {
      humanSessions: 46210,
      uniqueBuyers: 668,
      guestOrders: 53,
      estimatedPopupSignups: 1320,
      estimatedPopupSignupBuyers: 59,
      popupAudienceBuyers: 173,
      popupAudienceRevenue: 12680,
    },
    popupAudience: {
      customers: 6420,
      activeEmailSubscribers: 5733,
      periodSignups: 1486,
      unclassifiedSignups: 96,
      multiSelect: true,
      segments: [
        { key: "deer", label: "Deer", customers: 545, share: 545 / 1486, periodBuyers: 32, buyerRate: 32 / 545, periodOrders: 35, periodRevenue: 2450, aov: 70 },
        { key: "turkey", label: "Turkey", customers: 410, share: 410 / 1486, periodBuyers: 21, buyerRate: 21 / 410, periodOrders: 23, periodRevenue: 1552.5, aov: 67.5 },
        { key: "freshwater", label: "Freshwater", customers: 335, share: 335 / 1486, periodBuyers: 18, buyerRate: 18 / 335, periodOrders: 20, periodRevenue: 1310, aov: 65.5 },
        { key: "saltwater", label: "Saltwater", customers: 260, share: 260 / 1486, periodBuyers: 11, buyerRate: 11 / 260, periodOrders: 12, periodRevenue: 822, aov: 68.5 },
        { key: "seasonal", label: "Seasonal", customers: 198, share: 198 / 1486, periodBuyers: 7, buyerRate: 7 / 198, periodOrders: 8, periodRevenue: 516, aov: 64.5 },
      ],
      selectionDepth: [
        { key: "one", label: "1 option", customers: 1010, share: 1010 / 1390, periodBuyers: 51, buyerRate: 51 / 1010, periodOrders: 58, periodRevenue: 3944, aov: 68 },
        { key: "two", label: "2 options", customers: 302, share: 302 / 1390, periodBuyers: 16, buyerRate: 16 / 302, periodOrders: 19, periodRevenue: 1311, aov: 69 },
        { key: "three_plus", label: "3+ options", customers: 78, share: 78 / 1390, periodBuyers: 4, buyerRate: 4 / 78, periodOrders: 5, periodRevenue: 360, aov: 72 },
      ],
      tagStateBasis: "current_customer_tags",
    },
    rates: {
      sessionToSignup: 1486 / 49560,
      signupToBuyer: 74 / 1486,
      sessionToSignupBuyer: 74 / 49560,
      popupAudienceBuyerRate: 198 / 6420,
    },
    buyerScope: "online_store",
    funnelBuyerScope: "online_store",
    signupDateBasis: "marketing_updated_at_then_customer_created_at_estimate",
    sample: true,
    coverage: {
      sessions: {
        state: "estimated",
        source: "Demo sample",
        reason: "Illustrative sample data for local visual QA; not Shopify production data.",
      },
      buyers: {
        state: "estimated",
        source: "Demo sample",
        reason: "Illustrative sample data for local visual QA; not Shopify production data.",
      },
      popupAudience: {
        state: "estimated",
        source: "Demo sample",
        reason: "Illustrative sample data for local visual QA; popup segments are multi-select.",
      },
    },
  },
  daily,
  products: [
    {
      id: "p-teton-map",
      title: "Grand Teton National Park Illustrated Map T-shirt",
      handle: "grand-teton-national-park-illustrated-map-t-shirt",
      imageUrl: productImages.tetonMap,
      productType: "T-Shirt",
      apparelType: "T-shirt / tee",
      theme: "National park / outdoor",
      designFamily: "Map / illustrated destination",
      collections: ["National Park", "Graphic Tee"],
      tags: ["outdoor", "map", "travel"],
      descriptionText: "Illustrated national park map tee for outdoor and travel buyers.",
      listingDate: "2026-05-22",
      currentSales: 5380,
      previousSales: 2810,
      currentOrders: 124,
      previousOrders: 70,
      unitsSold: 132,
      inventory: 220,
      daysOfCover: 23.3,
      confidence: 88,
      roas: 3.4,
      action: "scale",
      actionReason: "Revenue and orders are rising with enough order volume. Scale only with Meta ROAS guardrail.",
      source: "Product title",
      daily: productDaily(5380, 124),
    },
    {
      id: "p-trout-species",
      title: "Trout Species Of The Appalachian Mountains T-shirt",
      handle: "trout-species-of-the-appalachian-mountains-t-shirt",
      imageUrl: productImages.trout,
      productType: "T-Shirt",
      apparelType: "T-shirt / tee",
      theme: "Fishing / trout",
      designFamily: "Species chart",
      collections: ["Fishing", "Trout Fishing"],
      tags: ["fishing", "trout", "appalachian"],
      descriptionText: "Trout species design for summer fishing and regional outdoor buyers.",
      listingDate: "2026-06-01",
      currentSales: 4180,
      previousSales: 3570,
      currentOrders: 91,
      previousOrders: 81,
      unitsSold: 97,
      inventory: 118,
      daysOfCover: 17.0,
      confidence: 84,
      roas: 2.8,
      action: "scale",
      actionReason: "Fishing is in season and the product has stable daily order volume.",
      source: "Shopify collection",
      daily: productDaily(4180, 91),
    },
    {
      id: "p-mahi-strike",
      title: "Mahi Strike Offshore T-shirt",
      handle: "mahi-strike-offshore-t-shirt",
      imageUrl: productImages.mahi,
      productType: "T-Shirt",
      apparelType: "T-shirt / tee",
      theme: "Fishing / offshore",
      designFamily: "Fish action graphic",
      collections: ["Fishing", "Saltwater Fishing"],
      tags: ["mahi", "offshore", "summer"],
      descriptionText: "Bright offshore fishing design for warm-season fishing buyers.",
      listingDate: "2026-06-06",
      currentSales: 1220,
      previousSales: 980,
      currentOrders: 28,
      previousOrders: 24,
      unitsSold: 30,
      inventory: 72,
      daysOfCover: 33.6,
      confidence: 61,
      roas: 1.4,
      action: "watch",
      actionReason: "Early signal is positive, but order count and Meta efficiency are not strong enough for aggressive scaling.",
      source: "Product title",
      daily: productDaily(1220, 28),
    },
    {
      id: "p-wild-turkey",
      title: "Wild Turkey Run T-shirt",
      handle: "wild-turkey-run-t-shirt",
      imageUrl: productImages.turkey,
      productType: "T-Shirt",
      apparelType: "T-shirt / tee",
      theme: "Turkey hunting",
      designFamily: "Turkey wildlife graphic",
      collections: ["Turkey Hunting"],
      tags: ["turkey", "hunting"],
      descriptionText: "Turkey hunting print for spring gobbler and outdoor customers.",
      listingDate: "2026-05-03",
      currentSales: 2427,
      previousSales: 6420,
      currentOrders: 57,
      previousOrders: 138,
      unitsSold: 61,
      inventory: 84,
      daysOfCover: 20.7,
      confidence: 79,
      roas: 0.9,
      action: "fix",
      actionReason: "Mature enough to evaluate. Revenue dropped hard after the main spring turkey window.",
      source: "Shopify collection",
      daily: productDaily(2427, 57),
    },
    {
      id: "p-lake-time",
      title: "It's Lake Time T-shirt",
      handle: "its-lake-time-t-shirt",
      imageUrl: productImages.lake,
      productType: "T-Shirt",
      apparelType: "T-shirt / tee",
      theme: "Lake lifestyle",
      designFamily: "Text lifestyle",
      collections: ["Fishing", "Summer Lifestyle"],
      tags: ["lake", "summer", "fishing"],
      descriptionText: "Lake lifestyle tee for summer travel, boating, and fishing audiences.",
      listingDate: "2026-06-08",
      currentSales: 820,
      previousSales: 0,
      currentOrders: 19,
      previousOrders: 0,
      unitsSold: 21,
      inventory: 145,
      daysOfCover: 96.7,
      confidence: 48,
      roas: null,
      action: "watch",
      actionReason: "New listing. Keep testing before making a cut or scale call.",
      source: "Product title",
      daily: productDaily(820, 19),
    },
    {
      id: "p-off-hunting",
      title: "Off Hunting Season T-shirt",
      handle: "off-hunting-season-t-shirt",
      imageUrl: productImages.hunting,
      productType: "T-Shirt",
      apparelType: "T-shirt / tee",
      theme: "Hunting lifestyle",
      designFamily: "Humor text graphic",
      collections: ["Hunting Lifestyle"],
      tags: ["hunting", "off season"],
      descriptionText: "Humor hunting tee with broad evergreen audience but lower current velocity.",
      listingDate: "2026-06-09",
      currentSales: 390,
      previousSales: 0,
      currentOrders: 9,
      previousOrders: 0,
      unitsSold: 10,
      inventory: 90,
      daysOfCover: null,
      confidence: 37,
      roas: null,
      action: "watch",
      actionReason: "Too few orders for a strong decision. Needs more daily data.",
      source: "Product title",
      daily: productDaily(390, 9),
    },
  ],
  blankPerformance: [
    { label: "T-shirt / tee", revenue: 9120, orders: 211, products: 46 },
    { label: "Hoodie", revenue: 3220, orders: 42, products: 18 },
    { label: "Long sleeve", revenue: 1520, orders: 31, products: 12 },
    { label: "Hat / cap", revenue: 940, orders: 29, products: 8 },
    { label: "Tank top", revenue: 420, orders: 15, products: 6 },
  ],
  themes: [
    { theme: "Fishing / trout", status: "In season", revenue: 4180, share: 0.22, products: 8 },
    { theme: "National park / outdoor", status: "In season", revenue: 5380, share: 0.28, products: 12 },
    { theme: "Turkey hunting", status: "Off-season", revenue: 2427, share: 0.13, products: 16 },
    { theme: "Lake lifestyle", status: "In season", revenue: 820, share: 0.04, products: 5 },
    { theme: "Father's Day gifting", status: "Event", revenue: 1290, share: 0.07, products: 4 },
  ],
};
